import { describe, expect, it } from "vitest";
import { classifyPage } from "./local-classifier";
import type { PageSafetySignals } from "../shared/page-safety-signals";
const base = (overrides: Partial<PageSafetySignals>): PageSafetySignals => ({ hostname: "example.com", title: "welcome", metaDescription: "", headings: [], visibleText: "", hasPasswordField: false, formCount: 0, externalLinkCount: 0, downloadLinkCount: 0, suspiciousDownloadExtensions: [], loginTerms: [], paymentTerms: [], ...overrides });
const cases: [string, Partial<PageSafetySignals>, string][] = [
  ["adult title", { title: "porn explicit videos" }, "ADULT"], ["adult headings", { headings: ["live cam porn"] }, "ADULT"], ["adult text", { visibleText: "porn xxx adult chat explicit videos" }, "ADULT"], ["adult duplicate", { title: "porn porn porn" }, "ADULT"], ["adult uncertain", { visibleText: "xxx" }, "UNKNOWN"],
  ["gambling casino", { title: "online casino sports betting" }, "GAMBLING"], ["gambling roulette", { title: "live roulette slot machine" }, "GAMBLING"], ["gambling bonus", { visibleText: "online casino deposit bonus place your bet" }, "GAMBLING"], ["gambling headings", { headings: ["sports betting live roulette"] }, "GAMBLING"], ["gambling weak", { visibleText: "casino" }, "UNKNOWN"],
  ["phishing credentials", { title: "verify your account confirm your password", hasPasswordField: true, loginTerms: ["password"], paymentTerms: ["payment"] }, "PHISHING"], ["phishing suspension", { title: "account suspended sign in immediately", hasPasswordField: true, loginTerms: ["sign in"], paymentTerms: ["billing"] }, "PHISHING"], ["phishing headings", { headings: ["verify your account", "confirm your password"] }, "PHISHING"], ["phishing weak", { visibleText: "security alert" }, "SAFE"], ["phishing tutorial", { title: "cybersecurity tutorial", visibleText: "This tutorial explains how phishing attacks work and prevention." }, "UNKNOWN"],
  ["scam profit", { title: "guaranteed profit claim your prize" }, "SCAM"], ["scam transfer", { title: "wire transfer pay a fee" }, "SCAM"], ["scam urgency", { visibleText: "guaranteed profit act now limited time offer" }, "SCAM"], ["scam weak", { visibleText: "act now" }, "SAFE"], ["scam news", { title: "news research", visibleText: "news report about guaranteed profit scams" }, "UNKNOWN"],
  ["drugs sale", { title: "buy cocaine buy heroin" }, "DRUGS"], ["drugs delivery", { title: "order opioids drug delivery" }, "DRUGS"], ["drugs text", { visibleText: "buy cocaine illegal drugs drug delivery" }, "DRUGS"], ["drugs medical", { title: "medical research", visibleText: "Medical research discusses drug addiction treatment and recovery." }, "SAFE"], ["drugs legal", { title: "legal information", visibleText: "legal research on illegal drugs" }, "UNKNOWN"],
  ["violence graphic", { title: "graphic violence execution video" }, "GRAPHIC_VIOLENCE"], ["violence gore", { title: "gore video graphic violence" }, "GRAPHIC_VIOLENCE"], ["extremism", { title: "violent extremist terrorist propaganda" }, "HATE_EXTREMISM"], ["violence history", { title: "history lesson", visibleText: "history lesson discusses graphic violence" }, "UNKNOWN"], ["violence weak", { visibleText: "violence" }, "SAFE"],
  ["download executable", { title: "download cracked free keygen", downloadLinkCount: 1, suspiciousDownloadExtensions: ["exe"] }, "SUSPICIOUS_DOWNLOAD"], ["download msi", { title: "download exe install now", downloadLinkCount: 2, suspiciousDownloadExtensions: ["msi"] }, "SUSPICIOUS_DOWNLOAD"], ["download apk", { visibleText: "download cracked free keygen", downloadLinkCount: 1, suspiciousDownloadExtensions: ["apk"] }, "SUSPICIOUS_DOWNLOAD"], ["download weak", { downloadLinkCount: 1 }, "SAFE"], ["download normal", { title: "software documentation", downloadLinkCount: 1, suspiciousDownloadExtensions: ["zip"] }, "SAFE"],
  ["safe school", { title: "school mathematics", visibleText: "A lesson about numbers and science." }, "SAFE"], ["safe medical", { title: "hospital appointment", visibleText: "health information" }, "SAFE"], ["unknown conflicting", { title: "online casino porn" }, "UNKNOWN"], ["unknown short", { title: "welcome" }, "SAFE"], ["unknown research", { title: "academic research", visibleText: "research paper about gambling laws in the 1800s" }, "UNKNOWN"]
];
describe("local classifier", () => {
  it.each(cases)("classifies %s", (_name, signals, expected) => expect(classifyPage(base(signals)).category).toBe(expected));
  it("caps confidence scores", () => expect(classifyPage(base({ title: "porn porn porn online casino sports betting buy cocaine buy heroin" })).confidence).toBeLessThanOrEqual(1));
  it("returns structured score entries", () => expect(classifyPage(base({})).categoryScores).toHaveProperty("UNKNOWN"));
});
